-- Full current schema. Nothing applies this file automatically: it is kept
-- in sync by hand as each migration in migrations/ lands, and it is a
-- *description* of the live databases rather than the thing that created
-- them. See CLAUDE.md, "Data model".
--
-- That gap has bitten once already and is worth stating plainly. The
-- earliest tables predate migrations/ entirely - they were created by hand
-- and this file was written afterwards to describe them - so it declared an
-- ON DELETE CASCADE on asset_repairs.asset_id that production never
-- actually had, and deleting an asset with repairs failed in production for
-- months. Migration 0006 fixed the database; nothing had been wrong with
-- this file. The e2e project, created later *from* this file, had it right
-- all along, which is exactly why the test suite never noticed.
--
-- So: a change here is not a change to any database, and agreement between
-- this file and a database is an assumption until someone checks it. The
-- query at the bottom of 0006 is the cheap way to check the delete rules.

create table assets (
  id uuid primary key default gen_random_uuid(),
  -- User-facing identifier ("Item-01", "Item-02", ...) formatted client-side
  -- from this number. `generated always as identity` is sequence-backed, so
  -- it's assigned atomically at insert time, based on the highest number
  -- ever issued rather than how many rows currently exist - deleting an
  -- asset never frees up its number for reuse.
  asset_number bigint generated always as identity,
  asset_name text not null,
  description text not null,
  recorded_at timestamptz not null default now(),   -- the user-facing "Date/time" field: pre-populated client-side, editable
  -- No photo column here: an asset's photos are rows in asset_photos.
  -- A single photo_path lived here until 0005 dropped it.
  -- Current state only, both nullable - every asset that predates this
  -- feature has neither, and there's no sensible value to backfill.
  -- Stored lowercase ('good'/'ok'/'poor'); display casing is a client-side
  -- concern (format.js), not baked into the stored value or the check
  -- constraint. No history is kept - editing overwrites the previous
  -- value, same trade-off as any other "current state" field here.
  condition text check (condition in ('good', 'ok', 'poor')),
  condition_note text check (condition_note is null or length(condition_note) <= 200),
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- `default now()` on updated_at only fires on insert, not on later edits —
-- without this trigger it would silently keep showing the creation time
-- forever, even after a real edit.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger assets_set_updated_at
  before update on assets
  for each row
  execute function set_updated_at();

-- Comments are a running log, not a field that gets overwritten — one row
-- per comment, each carrying its own timestamp.
create table asset_comments (
  id bigint generated by default as identity primary key,
  -- on delete cascade added by 0006. The table is unused, so this has
  -- never blocked anything - but it would the day someone wired it up,
  -- exactly as asset_repairs did.
  asset_id uuid references assets(id) on delete cascade not null,
  comment text not null,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now()
);

create index asset_comments_asset_id_idx on asset_comments (asset_id);

-- Up to four photos per asset (the ceiling is enforced client-side, in
-- validation.js - see CLAUDE.md for why it isn't enforced here). uuid id
-- for the same reason as asset_repairs: the client generates it offline
-- and Supabase stores that same value, so there's no reconciliation step.
-- position is a sort key, not a count - removing a photo leaves a gap
-- rather than renumbering the rows that didn't change, which two offline
-- devices would otherwise do differently.
create table asset_photos (
  id uuid primary key default gen_random_uuid(),
  -- on delete cascade, same as asset_repairs. Note this drops the rows
  -- but not the Storage objects behind them - see CLAUDE.md's
  -- orphaned-file limitation.
  asset_id uuid references assets(id) on delete cascade not null,
  storage_path text not null,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

create index asset_photos_asset_id_idx on asset_photos (asset_id);

-- Repairs are a log, not a single flag: an asset can have several repair
-- records over its life, each independently editable and markable as
-- completed. uuid (not identity) so the client can generate the id offline
-- the same way it does for assets, with no reconciliation step once it syncs.
create table asset_repairs (
  id uuid primary key default gen_random_uuid(),
  -- on delete cascade: deleting an asset deletes its repair history with
  -- it, atomically at the DB level rather than as two separate client
  -- calls with a partial-failure window between them.
  asset_id uuid references assets(id) on delete cascade not null,
  description text not null,
  reported_at timestamptz not null default now(),
  completed_at timestamptz,                          -- null while outstanding; set when marked done
  created_by uuid references auth.users(id) default auth.uid(),
  -- auth.users isn't queryable client-side via RLS, so the email is also
  -- captured directly at save time - lets the UI show "Added by" without
  -- an extra join/permission the client doesn't have.
  created_by_email text not null,
  created_at timestamptz not null default now(),
  -- Null until the description is actually edited - distinct from
  -- created_at/created_by_email, so the UI can show who added a repair
  -- versus who last edited it, rather than one timestamp implying both.
  updated_at timestamptz,
  updated_by_email text,
  -- Same pattern as updated_at/updated_by_email: null until the repair
  -- is actually marked complete.
  completed_by_email text
);

create index asset_repairs_asset_id_idx on asset_repairs (asset_id);

-- A thread, not a single field — a repair can pick up more than one
-- comment over its life (the completion comment is just its first
-- entry). uuid id, same reasoning as asset_repairs: the client can
-- generate it offline with no reconciliation step once it syncs.
create table repair_comments (
  id uuid primary key default gen_random_uuid(),
  repair_id uuid references asset_repairs(id) on delete cascade not null,
  comment text not null,
  created_by_email text not null,
  -- Snapshotted at comment-creation time from the author's own profile,
  -- same reasoning as created_by_email: there's no client-side RLS access
  -- to look up *another* user's name later, so the display name has to be
  -- captured once, at the moment it's known. Null for an account with no
  -- name on file yet - the UI falls back to created_by_email in that case.
  created_by_name text,
  created_at timestamptz not null default now()
);

create index repair_comments_repair_id_idx on repair_comments (repair_id);

alter table assets enable row level security;

create policy "Logged-in users can manage all assets"
  on assets for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table asset_comments enable row level security;

create policy "Logged-in users can manage all comments"
  on asset_comments for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table asset_repairs enable row level security;

create policy "Logged-in users can manage all repairs"
  on asset_repairs for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table repair_comments enable row level security;

create policy "Logged-in users can manage all repair comments"
  on repair_comments for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table asset_photos enable row level security;

-- `for all` covers delete explicitly, which removing a photo from a
-- saved asset depends on.
create policy "Logged-in users can manage all asset photos"
  on asset_photos for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

-- One row per auth.users account, added lazily rather than backfilled.
-- Nullable by design: mandatory-ness for new signups is enforced at the
-- application layer (the signup form and the post-login prompt), not
-- here - a null name is the marker for "hasn't provided one yet", not an
-- error state. The CHECK constraints are the "never trust the client
-- alone" half: they only fire on a *non-null* value, so they can't be
-- used to force a name in, only to reject a malformed one.
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text,
  last_name text,
  -- chr(39) (a plain apostrophe) is concatenated in rather than embedded
  -- as a literal quote character in the pattern string - both '' quote-
  -- doubling and $tag$ dollar-quoting turned out to be easy things for
  -- copy/paste (or markdown/math rendering) to mangle into a syntax
  -- error, as did wrapping these across multiple lines - so each
  -- constraint is kept to one single, unbroken line.
  check (first_name is null or (first_name = btrim(first_name) and length(first_name) between 1 and 50 and first_name ~ ('^[[:alpha:][:space:]' || chr(39) || '-]+$'))),
  check (last_name is null or (last_name = btrim(last_name) and length(last_name) between 1 and 50 and last_name ~ ('^[[:alpha:][:space:]' || chr(39) || '-]+$')))
);

-- Populates a profiles row for every new account the moment it's created
-- - before email confirmation, before any login, so no authenticated
-- session/RLS check is available yet at that point. Covers both signup
-- paths: email/password (first_name/last_name arrive via signUp()'s
-- `options.data`, landing in raw_user_meta_data) and Google OAuth (no
-- such metadata, so the row is created with null names - which is
-- exactly what puts that account through the same post-login prompt as
-- a pre-existing legacy user). SECURITY DEFINER is what lets this insert
-- bypass RLS, since it runs as the trigger's owner, not the new user.
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (
    new.id,
    new.raw_user_meta_data ->> 'first_name',
    new.raw_user_meta_data ->> 'last_name'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function handle_new_user();

alter table profiles enable row level security;

create policy "Users can view their own profile"
  on profiles for select
  using (auth.uid() = id);

create policy "Users can insert their own profile"
  on profiles for insert
  with check (auth.uid() = id);

-- Restricted to rows where both names are still null, so this can only
-- ever fill a name in, never silently overwrite one that's already set.
create policy "Users can set their own name once"
  on profiles for update
  using (auth.uid() = id and first_name is null and last_name is null)
  with check (auth.uid() = id);

-- Tracks remaining legacy accounts still to be prompted. Progress query:
--   select count(*) from profiles where first_name is null or last_name is null;
create index profiles_missing_name_idx on profiles (id) where first_name is null or last_name is null;

-- Storage policies live on storage.objects, separate from the table
-- policies above - creating the asset-photos bucket itself grants no
-- access at all by default. Same shared-register pattern as the other
-- tables: any logged-in user can upload/read/replace/delete any photo.
--
-- This block used to claim the policy "already existed on the production
-- project, set up directly in the dashboard". It did not. Production had
-- RLS enabled on storage.objects with zero policies, so every photo
-- upload had been failing since the beginning - issue #97, migration
-- 0007. And the bucket was not empty but absent: production had no
-- buckets at all, found on 2026-08-08 when 0007's policy alone changed
-- nothing and photos still didn't arrive. 0007 creates the policy, 0008
-- the bucket underneath it, and a policy naming a bucket_id that no
-- bucket has is accepted without complaint. Only the e2e project ever had
-- either, the bucket by hand and the policy from
-- migrations/e2e-storage-policy.sql, which is why the Playwright suite
-- could assert photos reach Storage and pass throughout.
--
-- `for all` is deliberate: an owner-scoped delete would break photo
-- removal for anyone who didn't upload the file - the same bug in a
-- different action. The bucket must stay private; a public bucket would
-- "fix" access by removing it.
-- The bucket itself, missing from this file until 2026-08-08 - everything
-- above described access rules for something only e2e had. Declared
-- before the policy, since the policy is accepted either way.
insert into storage.buckets (id, name, public)
  values ('asset-photos', 'asset-photos', false)
  on conflict (id) do nothing;

create policy "Logged-in users can manage asset photos"
  on storage.objects for all
  using (bucket_id = 'asset-photos' and auth.uid() is not null)
  with check (bucket_id = 'asset-photos' and auth.uid() is not null);
