create table assets (
  id uuid primary key default gen_random_uuid(),
  -- User-facing identifier ("Item-01", "Item-02", ...) formatted client-side
  -- from this number. `generated always as identity` is sequence-backed, so
  -- it's assigned atomically at insert time, based on the highest number
  -- ever issued rather than how many rows currently exist - deleting an
  -- asset never frees up its number for reuse.
  asset_number bigint generated always as identity,
  asset_name text not null,
  description text not null,
  recorded_at timestamptz not null default now(),   -- the user-facing "Date/time" field: pre-populated client-side, editable
  photo_path text,                                   -- object path in Supabase Storage
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- `default now()` on updated_at only fires on insert, not on later edits —
-- without this trigger it would silently keep showing the creation time
-- forever, even after a real edit.
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger assets_set_updated_at
  before update on assets
  for each row
  execute function set_updated_at();

-- Comments are a running log, not a field that gets overwritten — one row
-- per comment, each carrying its own timestamp.
create table asset_comments (
  id bigint generated by default as identity primary key,
  asset_id uuid references assets(id) not null,
  comment text not null,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now()
);

create index asset_comments_asset_id_idx on asset_comments (asset_id);

-- Repairs are a log, not a single flag: an asset can have several repair
-- records over its life, each independently editable and markable as
-- completed. uuid (not identity) so the client can generate the id offline
-- the same way it does for assets, with no reconciliation step once it syncs.
create table asset_repairs (
  id uuid primary key default gen_random_uuid(),
  -- on delete cascade: deleting an asset deletes its repair history with
  -- it, atomically at the DB level rather than as two separate client
  -- calls with a partial-failure window between them.
  asset_id uuid references assets(id) on delete cascade not null,
  description text not null,
  reported_at timestamptz not null default now(),
  completed_at timestamptz,                          -- null while outstanding; set when marked done
  created_by uuid references auth.users(id) default auth.uid(),
  -- auth.users isn't queryable client-side via RLS, so the email is also
  -- captured directly at save time - lets the UI show "Added by" without
  -- an extra join/permission the client doesn't have.
  created_by_email text not null,
  created_at timestamptz not null default now(),
  -- Null until the description is actually edited - distinct from
  -- created_at/created_by_email, so the UI can show who added a repair
  -- versus who last edited it, rather than one timestamp implying both.
  updated_at timestamptz,
  updated_by_email text
);

create index asset_repairs_asset_id_idx on asset_repairs (asset_id);

alter table assets enable row level security;

create policy "Logged-in users can manage all assets"
  on assets for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table asset_comments enable row level security;

create policy "Logged-in users can manage all comments"
  on asset_comments for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);

alter table asset_repairs enable row level security;

create policy "Logged-in users can manage all repairs"
  on asset_repairs for all
  using (auth.uid() is not null)
  with check (auth.uid() is not null);
